networks:
  matcha:
    name: matcha
    driver: bridge

services:
  front:
     container_name: front
     restart: "no"
     build:
      context: .
      dockerfile: front/Dockerfile
     networks:
      - matcha
     ports:
       - "8000:8000"
     extra_hosts:
      - "host.docker.internal:host-gateway"
     volumes:
      - vol_front:/app/front


volumes:
  vol_front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./front"