version: "3.8"

services:
  db:
    image: postgres:15
    container_name: matcha-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234qwer
      POSTGRES_DB: matcha_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
